Update code to make DRY
intern-space-program/avionics pull request #20
Opened 2019-11-22 18:11 UTC by xxEoD2242

Check this out.

2019-11-22 18:11 UTC, xxEoD2242 commented
This needs to be tested with the full system. Confident of my work but never leave it to chance.

2019-11-24 21:31 UTC, mdbernard commented
Line 245/246:

`GPS_CONNECTED = true;`
`if (GPS_CONNECTED) {`

This if block will always execute. If it's always supposed to execute, remove line 245 and the if check. If it's only supposed to execute when the condition is true, remove line 245. Either way, that line needs to go.

2019-11-24 21:34 UTC, mdbernard commented
There are 3 sensor setup functions: `set_up_gps`, `set_up_bmp`, and `set_up_bno`. Each of them does different things, which make sense if each sensor has a different setup procedure. However, there's also a function `check_for_bmp_status`, which does the same thing for the BMP as `set_up_bno` does for the BNO. These functions ought to be named consistently.

Corollary to that, since both the BMP and BNO have a connection check with a timeout (in `check_for_bmp_status` and `set_up_bno`, respectively), these could both be done in the same loop. Should the GPS sensor have a similar connection timeout check?

2019-11-24 21:39 UTC, mdbernard commented
One of the principles of functional programming is that a function does the exact same thing given the same inputs every time it is called. However, `sample_data_and_build_json_packet` does not do this. Its behavior depends on global variables, which it changes the value of.

In effect, this function is being used inside the `setup` function to determine whether it should do its job. It's its own validator. This is not ideal.

Instead, this function ought to be broken up into at least 3 different ones:
- `create_json_packet`
- `sample_sensors`
- `set_sensor_status_flags`
- `send_data`

Then `setup` isn't calling `sample_data_and_build_json_packet` to determine whether `sample_data_and_build_json_packet` should do its job.

2019-11-24 21:44 UTC, mdbernard commented
Line 44/45 and 49/50:
```double gps_base_altitude = 0;                         // Memory location for GPS base altitude
double* gps_alti_offset_address = &gps_base_altitude; // Offset for the GPS for launch reference frame```
```double base_altitude = 0;                     // Memory location for the offset for the BMP
double* alti_offset_address = &base_altitude; // Offset for the base altitude for the BMP```
The second variable in either of these is the memory location, and the first is the offset. Comments ought to be corrected. Also, not entirely sure why both are needed; I'd appreciate an explanation.

2019-11-24 21:46 UTC, mdbernard commented
Line 60: `// Function definitions`
These are function declarations, the definitions are at the bottom.

2019-11-24 21:47 UTC, mdbernard commented
Lines 56/57:
```
imu::Vector<3> vaccel;        // 3-dimensional Vector acceleration (non-conservative)
imu::Vector<3> laccel;        // 3-dimensional Vector acceleration (conservative)
```
These variable names ought to be more descriptive. For example, `accel_nc` and `accel_c` would work.

2019-11-24 21:50 UTC, mdbernard requested changes

2019-11-24 21:50 UTC, mdbernard commented on teensy/teensy_main/teensy_main.ino
> +    if (SEND_DATA)
This is not ideal. Why do this check every time if `SEND_DATA` is only getting set to true in `setup`, and never changing again? See comment for more details.

2019-11-24 21:50 UTC, mdbernard commented on teensy/teensy_main/teensy_main.ino
> +void sample_data_and_build_json_packet(){
If you find yourself using the word `and` in a function name, it would probably be wise split the functionality into multiple functions.

2019-11-24 21:50 UTC, mdbernard commented on teensy/teensy_main/teensy_main.ino
> +      serializeJson(doc, piSerial);
This is, in effect, the "main" thing the Teensy does from the Raspi's perspective. The main functionality really shouldn't be a sub-part of another big function with a condition checking whether or not to do it.

2019-11-24 21:52 UTC, mdbernard requested changes
Please see PR comments for more details on requested changes and minor changes to make.

2019-11-24 21:54 UTC, mdbernard commented
Out of curiosity, would it be possible to split this into multiple scripts? For example, this one could be called `main.ino`, and contain just includes, `setup`, and `loop`. Sensor-specific setups could be contained in their respective scripts. JSON-handling functions could also go in their own script.

This would make it much easier for the next programmer to change and add on to.

2019-11-24 22:34 UTC, xxEoD2242 commented
Unfortunately, it cannot, as the boot loader for the Teensy will only accept one file unless we wrote a library for each, which is overkill for what this actually does, in my opinion.

2019-11-24 22:36 UTC, mdbernard commented
> Unfortunately, it cannot, as the boot loader for the Teensy will only accept one file unless we wrote a library for each, which is overkill for what this actually does, in my opinion.

I mean, at the top, we have includes, so the main script could include the rest. Is that prohibited?

2019-11-25 13:13 UTC, xxEoD2242 commented
Shouldn’t be. I’d have to go look at how it includes the binaries but I think we could should just add them in as libraries through the Arduino IDE and call them just like the other ones. I’ll look at it and comment here.

2019-11-25 13:24 UTC, xxEoD2242 commented
So the real issue with multiple files is that the IDE compiler doesn’t work like a normal GCC compiler and actually compiles code from a different directory. A lot of people have been looking for solutions but the limitations of the IDE are what they are. You can create a library but, again, for what we have it may be overkill unless we move to not doing JSON and want to do custom structures.

2020-02-18 02:39 UTC, mdbernard commented
Merging for the sake of getting all this into one place for future review/use.

2020-02-18 02:39 UTC, merged